name: bangla_converter
description: Flutter package for convert Bangla Number to English Number or vice versa.
version: 0.0.1
# author: Pritom Chaki<hello.pritom.chaki@gmail.com>
homepage: https://github.com/Pritom-Chaki/bangla_converter
repository: https://github.com/Pritom-Chaki/bangla_converter


environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

